
version: 2.1


jobs:
  build:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run:
          name: npm build
          command: "npm i"
      - run: "npm run build"

workflows:
  build-test-analyze:
    jobs:
      - build
