
version: 2.1


jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-pack"
          paths:
           - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
         keys:
           - "npm-pack"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
         keys:
           - "npm-pack"
      - run: npm audit


workflows:
  build-test-analyze:
    jobs:
      - build
      - test:
         requires:
            - build
      - analyze:
         requires:
           - test 
